before:
  hooks:
  - go mod tidy
  - go generate ./...
builds:
- binary: trelldo
  env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  goos:
  - linux
  - windows
  - darwin
  - freebsd
  - openbsd
  goarch:
  - amd64
  - arm64
  - arm
  - 386
  goarm:
  - 6
  - 7
universal_binaries:
- replace: true
archives:
- format_overrides:
  - goos: windows
    format: zip
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
